// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"database/sql"
	"time"
)

type Project struct {
	ID        int32     `json:"id"`
	Title     string    `json:"title"`
	Info      string    `json:"info"`
	OwnerID   int32     `json:"owner_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Task struct {
	ID        int32        `json:"id"`
	ProjectID int32        `json:"project_id"`
	Title     string       `json:"title"`
	Info      string       `json:"info"`
	Tag       string       `json:"tag"`
	CreatedAt sql.NullTime `json:"created_at"`
	Beggining sql.NullTime `json:"beggining"`
	Deadline  sql.NullTime `json:"deadline"`
	Color     string       `json:"color"`
}

type User struct {
	ID           int32     `json:"id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PassHash     string    `json:"pass_hash"`
	JoinDate     time.Time `json:"join_date"`
	Bio          string    `json:"bio"`
	ProfilePhoto string    `json:"profile_photo"`
}

type Usersetting struct {
	ID       int32        `json:"id"`
	Darkmode sql.NullBool `json:"darkmode"`
}

type Usersinproject struct {
	ProjectID int32 `json:"project_id"`
	UserID    int32 `json:"user_id"`
}

type Usersintask struct {
	TaskID int32 `json:"task_id"`
	UserID int32 `json:"user_id"`
}
