// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: task.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/gofrs/uuid"
)

const createTask = `-- name: CreateTask :one

INSERT INTO tasks (
    project_id, title, info, tag, created_by, beggining, deadline, color
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING task_id, project_id, title, info, tag, created_by, created_at, beggining, deadline, color
`

type CreateTaskParams struct {
	ProjectID uuid.UUID      `json:"project_id"`
	Title     string         `json:"title"`
	Info      sql.NullString `json:"info"`
	Tag       sql.NullString `json:"tag"`
	CreatedBy uuid.UUID      `json:"created_by"`
	Beggining sql.NullTime   `json:"beggining"`
	Deadline  sql.NullTime   `json:"deadline"`
	Color     sql.NullString `json:"color"`
}

// TODO: auto time for beggining without input doesn't work.
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.queryRow(ctx, q.createTaskStmt, createTask,
		arg.ProjectID,
		arg.Title,
		arg.Info,
		arg.Tag,
		arg.CreatedBy,
		arg.Beggining,
		arg.Deadline,
		arg.Color,
	)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.ProjectID,
		&i.Title,
		&i.Info,
		&i.Tag,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Beggining,
		&i.Deadline,
		&i.Color,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE task_id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteTaskStmt, deleteTask, taskID)
	return err
}

const getTaskData = `-- name: GetTaskData :one
SELECT task_id, project_id, title, info, tag, created_by, created_at, beggining, deadline, color FROM tasks
WHERE task_id = $1
`

func (q *Queries) GetTaskData(ctx context.Context, taskID uuid.UUID) (Task, error) {
	row := q.queryRow(ctx, q.getTaskDataStmt, getTaskData, taskID)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.ProjectID,
		&i.Title,
		&i.Info,
		&i.Tag,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Beggining,
		&i.Deadline,
		&i.Color,
	)
	return i, err
}

const getTasksByProjectID = `-- name: GetTasksByProjectID :many
SELECT task_id, project_id, title, info, tag, created_by, created_at, beggining, deadline, color FROM tasks
WHERE project_id = $1 AND
      title =       COALESCE(NULLIF($4, ''), title) AND
      info =        COALESCE(NULLIF($5, ''), info) AND
      tag =         COALESCE(NULLIF($6, ''), tag) AND
      created_by =  COALESCE(NULLIF($7, uuid '00000000-0000-0000-0000-000000000000'), created_by) AND
      created_at >= COALESCE(NULLIF($8, timestamptz '0001-01-01 03:25:44+03:25:44'), created_at) AND
      created_at <= COALESCE(NULLIF($9, timestamptz '0001-01-01 03:25:44+03:25:44'), created_at) AND
      beggining >=  COALESCE(NULLIF($10, timestamptz '0001-01-01 03:25:44+03:25:44'), beggining) AND
      beggining <=  COALESCE(NULLIF($11, timestamptz '0001-01-01 03:25:44+03:25:44'), beggining) AND
      deadline >=   COALESCE(NULLIF($12, timestamptz '0001-01-01 03:25:44+03:25:44'), deadline) AND
      deadline <=   COALESCE(NULLIF($13, timestamptz '0001-01-01 03:25:44+03:25:44'), deadline)
ORDER BY
  CASE WHEN $14 = 'asc' THEN
    CASE
      WHEN $15 = 'created_at' THEN created_at
      WHEN $15 = 'beggining' THEN beggining
      WHEN $15 = 'deadline' THEN deadline
    END
  END ASC,
  CASE WHEN $14 = 'desc' THEN
    CASE
      WHEN $15 = 'created_at' THEN created_at
      WHEN $15 = 'beggining' THEN beggining
      WHEN $15 = 'deadline' THEN deadline
    END
  END DESC
LIMIT $2
OFFSET $3
`

type GetTasksByProjectIDParams struct {
	ProjectID      uuid.UUID   `json:"project_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
	Title          interface{} `json:"title"`
	Info           interface{} `json:"info"`
	Tag            interface{} `json:"tag"`
	CreatedBy      interface{} `json:"created_by"`
	CreatedAtFrom  interface{} `json:"created_at_from"`
	CreatedAtUntil interface{} `json:"created_at_until"`
	BegginingFrom  interface{} `json:"beggining_from"`
	BegginingUntil interface{} `json:"beggining_until"`
	DeadlineFrom   interface{} `json:"deadline_from"`
	DeadlineUntil  interface{} `json:"deadline_until"`
	Sortdirection  interface{} `json:"sortdirection"`
	Sortby         interface{} `json:"sortby"`
}

func (q *Queries) GetTasksByProjectID(ctx context.Context, arg GetTasksByProjectIDParams) ([]Task, error) {
	rows, err := q.query(ctx, q.getTasksByProjectIDStmt, getTasksByProjectID,
		arg.ProjectID,
		arg.Limit,
		arg.Offset,
		arg.Title,
		arg.Info,
		arg.Tag,
		arg.CreatedBy,
		arg.CreatedAtFrom,
		arg.CreatedAtUntil,
		arg.BegginingFrom,
		arg.BegginingUntil,
		arg.DeadlineFrom,
		arg.DeadlineUntil,
		arg.Sortdirection,
		arg.Sortby,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.ProjectID,
			&i.Title,
			&i.Info,
			&i.Tag,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Beggining,
			&i.Deadline,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one

UPDATE tasks SET
  title =     COALESCE(NULLIF($1, ''), title),
  info =      COALESCE(NULLIF($2, ''), info),
  tag =       COALESCE(NULLIF($3, ''), tag),
  beggining = COALESCE(NULLIF($4, timestamptz '0001-01-01 03:25:44+03:25:44'), beggining),
  deadline =  COALESCE(NULLIF($5, timestamptz '0001-01-01 03:25:44+03:25:44'), deadline),
  color =     COALESCE(NULLIF($6, ''), color)
WHERE task_id = $7
RETURNING task_id, project_id, title, info, tag, created_by, created_at, beggining, deadline, color
`

type UpdateTaskParams struct {
	Title     interface{} `json:"title"`
	Info      interface{} `json:"info"`
	Tag       interface{} `json:"tag"`
	Beggining interface{} `json:"beggining"`
	Deadline  interface{} `json:"deadline"`
	Color     interface{} `json:"color"`
	TaskID    uuid.UUID   `json:"task_id"`
}

// TODO: get tasks by filtering: title, tag, created_by, beggining, deadline
func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.queryRow(ctx, q.updateTaskStmt, updateTask,
		arg.Title,
		arg.Info,
		arg.Tag,
		arg.Beggining,
		arg.Deadline,
		arg.Color,
		arg.TaskID,
	)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.ProjectID,
		&i.Title,
		&i.Info,
		&i.Tag,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Beggining,
		&i.Deadline,
		&i.Color,
	)
	return i, err
}
